blank_issues_enabled: false

contact_links:
  - name: Questions & Discussions
    url: https://github.com/bewdes/LSPanel/discussions
    about: Ask questions, request help, and discuss LS Panel with the community.
